-- Pincode -> geographic coordinates. Saved separately so geocoding is done at most once per pincode.
CREATE TABLE pincode_location (
    pincode      VARCHAR(10)      NOT NULL,
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    place_name   VARCHAR(255),
    country      VARCHAR(2)       NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_pincode_location PRIMARY KEY (pincode)
);

-- One weather snapshot per (pincode, date). Repeat requests for the same pair are served from here.
CREATE TABLE weather_record (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pincode              VARCHAR(10)      NOT NULL,
    for_date             DATE             NOT NULL,
    temperature          DOUBLE PRECISION,
    feels_like           DOUBLE PRECISION,
    temp_min             DOUBLE PRECISION,
    temp_max             DOUBLE PRECISION,
    pressure             INTEGER,
    humidity             INTEGER,
    weather_main         VARCHAR(64),
    weather_description  VARCHAR(255),
    wind_speed           DOUBLE PRECISION,
    wind_degree          INTEGER,
    cloudiness           INTEGER,
    visibility           INTEGER,
    sunrise              TIMESTAMP WITH TIME ZONE,
    sunset               TIMESTAMP WITH TIME ZONE,
    observed_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    fetched_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    source               VARCHAR(32)      NOT NULL,
    CONSTRAINT pk_weather_record PRIMARY KEY (id),
    CONSTRAINT uq_weather_record_pincode_date UNIQUE (pincode, for_date),
    CONSTRAINT fk_weather_record_pincode FOREIGN KEY (pincode) REFERENCES pincode_location (pincode)
);

CREATE INDEX idx_weather_record_pincode ON weather_record (pincode);
